<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<p>这是我正在使用的SSM框架的pom文件，依赖会自动引入，使用版本锁定解决了版本冲突，提供给大家参考</p>
<p>请在使用时注意修改项目相关的信息</p>
<pre>
&lt;project xmlns="http://maven.apache.org/POM/4.0.0" 
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"&gt;
  &lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt;
  &lt;groupId&gt;com.msp&lt;/groupId&gt;
  &lt;artifactId&gt;mvn_twomek&lt;/artifactId&gt;
  &lt;version&gt;0.0.1-SNAPSHOT&lt;/version&gt;
  &lt;packaging&gt;pom&lt;/packaging&gt;
&lt;!-- 集中定义依赖版本号 --&gt;
	&lt;properties&gt;
		&lt;jstl.version&gt;1.2&lt;/jstl.version&gt;
		&lt;servlet-api.version&gt;2.5&lt;/servlet-api.version&gt;
		&lt;jsp-api.version&gt;2.0&lt;/jsp-api.version&gt;
		&lt;spring.version&gt;4.3.9.RELEASE&lt;/spring.version&gt;
		&lt;mybatis.version&gt;3.4.6&lt;/mybatis.version&gt;
		&lt;mybatis-spring.version&gt;1.3.1&lt;/mybatis-spring.version&gt;
		&lt;mybatis-ehcache.version&gt;1.1.0&lt;/mybatis-ehcache.version&gt;
		&lt;commons-dbcp.version&gt;1.4&lt;/commons-dbcp.version&gt;
		&lt;jackson-databind.version&gt;2.5.0&lt;/jackson-databind.version&gt;
		&lt;commons-fileupload.version&gt;1.2&lt;/commons-fileupload.version&gt;
		&lt;commons-io.version&gt;2.5&lt;/commons-io.version&gt;
		&lt;commons-lang3.version&gt;3.0&lt;/commons-lang3.version&gt;
		&lt;commons-logging.version&gt;1.2&lt;/commons-logging.version&gt;
		&lt;log4j.version&gt;1.2.17&lt;/log4j.version&gt;
		&lt;slf4j.version&gt;1.7.25&lt;/slf4j.version&gt;
	&lt;/properties&gt;

	&lt;!--版本锁定 --&gt;
	&lt;dependencyManagement&gt;
		&lt;dependencies&gt;
			&lt;!-- JSP相关 --&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;jstl&lt;/groupId&gt;
				&lt;artifactId&gt;jstl&lt;/artifactId&gt;
				&lt;version&gt;${jstl.version}&lt;/version&gt;
			&lt;/dependency&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;javax.servlet&lt;/groupId&gt;
				&lt;artifactId&gt;servlet-api&lt;/artifactId&gt;
				&lt;version&gt;${servlet-api.version}&lt;/version&gt;
				&lt;scope&gt;provided&lt;/scope&gt;
			&lt;/dependency&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;javax.servlet&lt;/groupId&gt;
				&lt;artifactId&gt;jsp-api&lt;/artifactId&gt;
				&lt;version&gt;${jsp-api.version}&lt;/version&gt;
				&lt;scope&gt;provided&lt;/scope&gt;
			&lt;/dependency&gt;

			&lt;!--spring相关 --&gt;
			&lt;!-- Spring --&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;org.springframework&lt;/groupId&gt;
				&lt;artifactId&gt;spring-context&lt;/artifactId&gt;
				&lt;version&gt;${spring.version}&lt;/version&gt;
			&lt;/dependency&gt;
			&lt;!--SpringMVC --&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;org.springframework&lt;/groupId&gt;
				&lt;artifactId&gt;spring-webmvc&lt;/artifactId&gt;
				&lt;version&gt;${spring.version}&lt;/version&gt;
			&lt;/dependency&gt;
			&lt;!--事务 --&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;org.springframework&lt;/groupId&gt;
				&lt;artifactId&gt;spring-jdbc&lt;/artifactId&gt;
				&lt;version&gt;${spring.version}&lt;/version&gt;
			&lt;/dependency&gt;
			&lt;!--aop --&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;org.springframework&lt;/groupId&gt;
				&lt;artifactId&gt;spring-aspects&lt;/artifactId&gt;
				&lt;version&gt;${spring.version}&lt;/version&gt;
			&lt;/dependency&gt;

			&lt;!--mybatis --&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;org.mybatis&lt;/groupId&gt;
				&lt;artifactId&gt;mybatis&lt;/artifactId&gt;
				&lt;version&gt;${mybatis.version}&lt;/version&gt;
			&lt;/dependency&gt;
			&lt;!--mybatis缓存 --&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;org.mybatis.caches&lt;/groupId&gt;
				&lt;artifactId&gt;mybatis-ehcache&lt;/artifactId&gt;
				&lt;version&gt;${mybatis-ehcache.version}&lt;/version&gt;
			&lt;/dependency&gt;
			&lt;!--mybatis-spring  --&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;org.mybatis&lt;/groupId&gt;
				&lt;artifactId&gt;mybatis-spring&lt;/artifactId&gt;
				&lt;version&gt;${mybatis-spring.version}&lt;/version&gt;
			&lt;/dependency&gt;

			&lt;!--数据源 --&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;commons-dbcp&lt;/groupId&gt;
				&lt;artifactId&gt;commons-dbcp&lt;/artifactId&gt;
				&lt;version&gt;${commons-dbcp.version}&lt;/version&gt;
			&lt;/dependency&gt;

			&lt;!--json --&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;com.fasterxml.jackson.core&lt;/groupId&gt;
				&lt;artifactId&gt;jackson-databind&lt;/artifactId&gt;
				&lt;version&gt;${jackson-databind.version}&lt;/version&gt;
			&lt;/dependency&gt;

			&lt;!--上传 --&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;commons-fileupload&lt;/groupId&gt;
				&lt;artifactId&gt;commons-fileupload&lt;/artifactId&gt;
				&lt;version&gt;${commons-fileupload.version}&lt;/version&gt;
			&lt;/dependency&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;commons-io&lt;/groupId&gt;
				&lt;artifactId&gt;commons-io&lt;/artifactId&gt;
				&lt;version&gt;${commons-io.version}&lt;/version&gt;
			&lt;/dependency&gt;

			&lt;!--commons工具类 --&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;org.apache.commons&lt;/groupId&gt;
				&lt;artifactId&gt;commons-lang3&lt;/artifactId&gt;
				&lt;version&gt;${commons-lang3.version}&lt;/version&gt;
			&lt;/dependency&gt;

			&lt;!--日志 --&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;commons-logging&lt;/groupId&gt;
				&lt;artifactId&gt;commons-logging&lt;/artifactId&gt;
				&lt;version&gt;${commons-logging.version}&lt;/version&gt;
			&lt;/dependency&gt;
			&lt;dependency&gt;
				&lt;groupId&gt;log4j&lt;/groupId&gt;
				&lt;artifactId&gt;log4j&lt;/artifactId&gt;
				&lt;version&gt;${log4j.version}&lt;/version&gt;
			&lt;/dependency&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;org.slf4j&lt;/groupId&gt;
			&lt;artifactId&gt;slf4j-api&lt;/artifactId&gt;
			&lt;version&gt;${slf4j.version}&lt;/version&gt;
		&lt;/dependency&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;org.slf4j&lt;/groupId&gt;
			&lt;artifactId&gt;slf4j-log4j12&lt;/artifactId&gt;
			&lt;version&gt;${slf4j.version}&lt;/version&gt;
		&lt;/dependency&gt;
		&lt;dependency&gt;
		    &lt;groupId&gt;org.springframework&lt;/groupId&gt;
		    &lt;artifactId&gt;spring-test&lt;/artifactId&gt;
			&lt;version&gt;${spring.version}&lt;/version&gt;
		&lt;/dependency&gt;
		&lt;/dependencies&gt;
	&lt;/dependencyManagement&gt;

	&lt;!-- 导入依赖 --&gt;
	&lt;dependencies&gt;
		&lt;!-- JSP相关 --&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;jstl&lt;/groupId&gt;
			&lt;artifactId&gt;jstl&lt;/artifactId&gt;
		&lt;/dependency&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;javax.servlet&lt;/groupId&gt;
			&lt;artifactId&gt;servlet-api&lt;/artifactId&gt;
			&lt;scope&gt;provided&lt;/scope&gt;
		&lt;/dependency&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;javax.servlet&lt;/groupId&gt;
			&lt;artifactId&gt;jsp-api&lt;/artifactId&gt;
			&lt;scope&gt;provided&lt;/scope&gt;
		&lt;/dependency&gt;

		&lt;!--spring相关 --&gt;
		&lt;!-- Spring --&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;org.springframework&lt;/groupId&gt;
			&lt;artifactId&gt;spring-context&lt;/artifactId&gt;
		&lt;/dependency&gt;
		&lt;!--SpringMVC --&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;org.springframework&lt;/groupId&gt;
			&lt;artifactId&gt;spring-webmvc&lt;/artifactId&gt;
		&lt;/dependency&gt;
		&lt;!--事务 --&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;org.springframework&lt;/groupId&gt;
			&lt;artifactId&gt;spring-jdbc&lt;/artifactId&gt;
		&lt;/dependency&gt;
		&lt;!--aop --&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;org.springframework&lt;/groupId&gt;
			&lt;artifactId&gt;spring-aspects&lt;/artifactId&gt;
		&lt;/dependency&gt;

		&lt;!--mybatis --&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;org.mybatis&lt;/groupId&gt;
			&lt;artifactId&gt;mybatis&lt;/artifactId&gt;
		&lt;/dependency&gt;
		&lt;!--mybatis缓存 --&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;org.mybatis.caches&lt;/groupId&gt;
			&lt;artifactId&gt;mybatis-ehcache&lt;/artifactId&gt;
		&lt;/dependency&gt;
		&lt;!--mybatis-spring  --&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;org.mybatis&lt;/groupId&gt;
			&lt;artifactId&gt;mybatis-spring&lt;/artifactId&gt;
		&lt;/dependency&gt;

		&lt;!--数据源，使用的是dbcp数据库连接池--&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;commons-dbcp&lt;/groupId&gt;
			&lt;artifactId&gt;commons-dbcp&lt;/artifactId&gt;
		&lt;/dependency&gt;

		&lt;!--json --&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;com.fasterxml.jackson.core&lt;/groupId&gt;
			&lt;artifactId&gt;jackson-databind&lt;/artifactId&gt;
		&lt;/dependency&gt;

		&lt;!--上传 --&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;commons-fileupload&lt;/groupId&gt;
			&lt;artifactId&gt;commons-fileupload&lt;/artifactId&gt;
		&lt;/dependency&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;commons-io&lt;/groupId&gt;
			&lt;artifactId&gt;commons-io&lt;/artifactId&gt;
		&lt;/dependency&gt;

		&lt;!--commons工具类 --&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;org.apache.commons&lt;/groupId&gt;
			&lt;artifactId&gt;commons-lang3&lt;/artifactId&gt;
		&lt;/dependency&gt;
			

		&lt;!--日志 --&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;commons-logging&lt;/groupId&gt;
			&lt;artifactId&gt;commons-logging&lt;/artifactId&gt;
		&lt;/dependency&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;log4j&lt;/groupId&gt;
			&lt;artifactId&gt;log4j&lt;/artifactId&gt;
		&lt;/dependency&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;org.slf4j&lt;/groupId&gt;
			&lt;artifactId&gt;slf4j-api&lt;/artifactId&gt;
		&lt;/dependency&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;org.slf4j&lt;/groupId&gt;
			&lt;artifactId&gt;slf4j-log4j12&lt;/artifactId&gt;
		&lt;/dependency&gt;

		&lt;!-- spring-junit --&gt;
		&lt;dependency&gt;
		    &lt;groupId&gt;org.springframework&lt;/groupId&gt;
		    &lt;artifactId&gt;spring-test&lt;/artifactId&gt;
		    &lt;scope&gt;test&lt;/scope&gt;
		&lt;/dependency&gt;
		&lt;!-- junit --&gt;
		&lt;dependency&gt;
		    &lt;groupId&gt;junit&lt;/groupId&gt;
		    &lt;artifactId&gt;junit&lt;/artifactId&gt;
		    &lt;version&gt;4.12&lt;/version&gt;
		    &lt;scope&gt;test&lt;/scope&gt;
		&lt;/dependency&gt;
		&lt;!-- https://mvnrepository.com/artifact/mysql/mysql-connector-java --&gt;
		&lt;dependency&gt;
		    &lt;groupId&gt;mysql&lt;/groupId&gt;
		    &lt;artifactId&gt;mysql-connector-java&lt;/artifactId&gt;
		    &lt;version&gt;5.1.6&lt;/version&gt;
		&lt;/dependency&gt;
	&lt;/dependencies&gt;
  	&lt;build&gt;
  	&lt;plugins&gt;
  		&lt;!-- 编译版本插件 --&gt;
  		&lt;plugin&gt;
  			&lt;groupId&gt;org.apache.maven.plugins&lt;/groupId&gt;
  			&lt;artifactId&gt;maven-compiler-plugin&lt;/artifactId&gt;
  			&lt;version&gt;3.2&lt;/version&gt;
  			&lt;configuration&gt;
  					&lt;encoding&gt;UTF-8&lt;/encoding&gt;
  					&lt;source&gt;1.7&lt;/source&gt;
  					&lt;target&gt;1.7&lt;/target&gt;
  			&lt;/configuration&gt;
  		&lt;/plugin&gt;
  		&lt;!-- 绑定tomcat7  用于tomcat的热部署--&gt;
  		&lt;plugin&gt;
			 &lt;groupId&gt;org.apache.tomcat.maven&lt;/groupId&gt;
			  &lt;artifactId&gt;tomcat7-maven-plugin&lt;/artifactId&gt;
			  &lt;version&gt;2.2&lt;/version&gt;
				&lt;configuration&gt;
						&lt;!--server与maven的setting.xml中的id一致--&gt;
						&lt;server&gt;tomcat&lt;/server&gt;
						&lt;!--url为tomcat管理地址--&gt;
						&lt;url&gt;http://localhost:8080/manager/text&lt;/url&gt;
				&lt;/configuration&gt;
		 &lt;/plugin&gt;
  	&lt;/plugins&gt;
  	&lt;/build&gt;
  	&lt;modules&gt;
  		&lt;module&gt;emp-model&lt;/module&gt;
  		&lt;module&gt;emp-dao&lt;/module&gt;
  		&lt;module&gt;emp-service&lt;/module&gt;
  		&lt;module&gt;emp-web&lt;/module&gt;
  		&lt;module&gt;twomek&lt;/module&gt;
  	&lt;/modules&gt;
&lt;/project&gt;

</pre>
<p>或者你可以点下面的连接直接下载：</p>
<p><a href="${pageContext.request.contextPath }/file/ssm_pom.xml" download="">ssm框架pom文件(非常抱歉，可能有部分浏览器不支持此链接)</a></p>